version: '3.8'

services:
    automatic1111:
        build:
            context: .
            args:
              - GROUP_ID=${GROUP_ID:-1000}
              - USER_ID=${USER_ID:-1000}
              - USER_NAME=${USER_NAME:-automatic1111}
              - PYTHON_VERSION=3.10.2
        user: ${USER_ID:-1000}:${GROUP_ID:-1000}
        volumes:
            - .:/workspace
            - home:/home
        ports:
            - "7860:7860"
        command: /workspace/webui.sh --listen --theme dark
        working_dir: /workspace
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]

volumes:
    home:
